### ISSUE TITLE
Albums.share Not Working?

### ISSUE THREAD

**Issue by doop24** [deivitaka/GPhotos#1]
GPhotos is great!!
But Album.share is not working for my environment.
(XCode 11.3.1, Swift5)

Error Message Below.
GPhotos E: Optional("Invalid JSON payload received. Unexpected token.\nsharedAlbumOptions%5\n^")

Please tell me how to fix this.

**Comment by deivitaka** [comment]
Resolved in 138e350. Thanks for the heads up.
