### ISSUE TITLE
Image Uploading Issue.

### ISSUE THREAD

**Issue by RazaulAnsari** [deivitaka/GPhotos#10]
Hello Team,

I'm using GPhotos to upload the images but i'm facing some issue. I have try to uploading the image second time, got correct response from api but the image not shown in the Google Photos. Could you please check and update me, how to solve this issue. 

Thank you.

**Comment by deivitaka** [comment]
Hi @RazaulAnsari, what response did you get from api? Can you reproduce this in the sample app?
