### ISSUE TITLE
Upload crashes if filenames array is not set

### ISSUE THREAD

**Issue by patricks** [deivitaka/GPhotos#5]
If I don't set a filenames array in the upload function, the function crashes at the following line:

`self.upload(image: images.popLast()!, filename: filenames.popLast()!) { (token) in`

As a workaround I create an array with empty filenames:

`let filenames = [String?](repeating: nil, count: images.count)`

**Comment by deivitaka** [comment]
@patricks thanks for the feedback. It should have been handled better.
Should be fixed d38345a
