### ISSUE TITLE
Push version 0.6.0 to cocopods repo

### ISSUE THREAD

**Issue by patricks** [deivitaka/GPhotos#6]
Please push the new version 0.6.0 to the cocoapods repo. So it can be installed via `pod update`

**Comment by deivitaka** [comment]
As silly as it is, can't update because I can't receive an email from cocoapods. Have tried to contact them, hopefully it can be fixed soon. In the meantime, maybe you can add the changes locally. Sorry for the trouble

**Comment by axelguilmin** [comment]
As a workaround you can use something like : 
```
pod 'GPhotos', :git => 'https://github.com/deivitaka/GPhotos', branch: 'master', commit: '8703c9223a55800730a21f059dd8e63830794962'
```

**Comment by deivitaka** [comment]
fyi: I was able to push version 0.6.0 today. thanks for the feedback
